In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings

train = pd.read_csv("train.csv")
warnings.filterwarnings('ignore')
#train.drop(['education'], axis=1,inplace=True)
#train.drop(['relationship'], axis=1,inplace=True)

%matplotlib inline

In [2]:
y_label = train['income']
train.drop(['income'], axis=1, inplace=True)

train = pd.get_dummies(train)

In [4]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

rf_clf = RandomForestClassifier(n_estimators=100,max_features='sqrt',max_depth=None,min_samples_split=2,bootstrap=True)
rf_scores = cross_val_score(rf_clf,train,y_label,cv=10)
rf_scores

array([0.85718255, 0.84690192, 0.85523757, 0.85023618, 0.85857183,
       0.85968325, 0.85273687, 0.85273687, 0.85829397, 0.85682513])

In [5]:
rf_clf.fit(train,y_label)
importances=rf_clf.feature_importances_
names=train.columns.values.tolist()
sort_lst=sorted(zip(map(lambda x: round(x,3),importances),names), reverse=True)
sort_lst
#importances

[(0.172, 'fnlwgt'),
 (0.158, 'Age'),
 (0.094, 'capital gain'),
 (0.086, 'hours per week'),
 (0.066, 'education-num'),
 (0.06, 'marital-status_Married-civ-spouse'),
 (0.043, 'relationship_Husband'),
 (0.031, 'capital loss'),
 (0.024, 'marital-status_Never-married'),
 (0.018, 'occupation_Exec-managerial'),
 (0.014, 'occupation_Prof-specialty'),
 (0.011, 'relationship_Not-in-family'),
 (0.011, 'gender'),
 (0.011, 'education_Bachelors'),
 (0.01, 'relationship_Wife'),
 (0.009, 'workclass_Private'),
 (0.009, 'relationship_Own-child'),
 (0.008, 'workclass_Self-emp-not-inc'),
 (0.008, 'race'),
 (0.008, 'occupation_Other-service'),
 (0.008, 'marital-status_Divorced'),
 (0.008, 'education_Masters'),
 (0.007, 'relationship_Unmarried'),
 (0.007, 'education_HS-grad'),
 (0.006, 'workclass_Self-emp-inc'),
 (0.006, 'occupation_Sales'),
 (0.006, 'occupation_Craft-repair'),
 (0.005, 'workclass_Local-gov'),
 (0.005, 'workclass_Federal-gov'),
 (0.005, 'occupation_Adm-clerical'),
 (0.005, 'native-country_United-States'),
 (0.005, 'education_Some-college'),
 (0.005, 'education_Prof-school'),
 (0.004, 'workclass_State-gov'),
 (0.004, 'occupation_Transport-moving'),
 (0.004, 'occupation_Tech-support'),
 (0.004, 'occupation_Machine-op-inspct'),
 (0.004, 'occupation_Farming-fishing'),
 (0.003, 'occupation_Protective-serv'),
 (0.003, 'occupation_Handlers-cleaners'),
 (0.003, 'education_Doctorate'),
 (0.003, 'education_Assoc-voc'),
 (0.002, 'workclass_?'),
 (0.002, 'occupation_?'),
 (0.002, 'native-country_Mexico'),
 (0.002, 'native-country_?'),
 (0.002, 'marital-status_Widowed'),
 (0.002, 'marital-status_Separated'),
 (0.002, 'education_Assoc-acdm'),
 (0.002, 'education_7th-8th'),
 (0.002, 'education_11th'),
 (0.002, 'education_10th'),
 (0.001, 'relationship_Other-relative'),
 (0.001, 'native-country_Poland'),
 (0.001, 'native-country_Italy'),
 (0.001, 'native-country_Germany'),
 (0.001, 'native-country_England'),
 (0.001, 'native-country_Cuba'),
 (0.001, 'native-country_Canada'),
 (0.001, 'marital-status_Married-spouse-absent'),
 (0.001, 'education_9th'),
 (0.001, 'education_5th-6th'),
 (0.001, 'education_12th'),
 (0.0, 'workclass_Without-pay'),
 (0.0, 'workclass_Never-worked'),
 (0.0, 'occupation_Priv-house-serv'),
 (0.0, 'occupation_Armed-Forces'),
 (0.0, 'native-country_Yugoslavia'),
 (0.0, 'native-country_Vietnam'),
 (0.0, 'native-country_Trinadad&Tobago'),
 (0.0, 'native-country_Thailand'),
 (0.0, 'native-country_Taiwan'),
 (0.0, 'native-country_South'),
 (0.0, 'native-country_Scotland'),
 (0.0, 'native-country_Puerto-Rico'),
 (0.0, 'native-country_Portugal'),
 (0.0, 'native-country_Philippines'),
 (0.0, 'native-country_Peru'),
 (0.0, 'native-country_Outlying-US(Guam-USVI-etc)'),
 (0.0, 'native-country_Nicaragua'),
 (0.0, 'native-country_Japan'),
 (0.0, 'native-country_Jamaica'),
 (0.0, 'native-country_Ireland'),
 (0.0, 'native-country_Iran'),
 (0.0, 'native-country_India'),
 (0.0, 'native-country_Hungary'),
 (0.0, 'native-country_Hong'),
 (0.0, 'native-country_Honduras'),
 (0.0, 'native-country_Holand-Netherlands'),
 (0.0, 'native-country_Haiti'),
 (0.0, 'native-country_Guatemala'),
 (0.0, 'native-country_Greece'),
 (0.0, 'native-country_France'),
 (0.0, 'native-country_El-Salvador'),
 (0.0, 'native-country_Ecuador'),
 (0.0, 'native-country_Dominican-Republic'),
 (0.0, 'native-country_Columbia'),
 (0.0, 'native-country_China'),
 (0.0, 'native-country_Cambodia'),
 (0.0, 'marital-status_Married-AF-spouse'),
 (0.0, 'education_Preschool'),
 (0.0, 'education_1st-4th')]

In [6]:
train_new = pd.read_csv("train.csv")
train_new.drop(['income'], axis=1,inplace=True)

new_country = []
for item in list(train_new['native-country']):
    if item != 'United-States':
        new_country.append('Others')
    else:
        new_country.append(item)
        

train_new['native-country'] = new_country
train_new = pd.get_dummies(train_new)

train_new

,Age,fnlwgt,education-num,race,gender,capital gain,capital loss,hours per week,workclass_?,workclass_Federal-gov,...,occupation_Tech-support,occupation_Transport-moving,relationship_Husband,relationship_Not-in-family,relationship_Other-relative,relationship_Own-child,relationship_Unmarried,relationship_Wife,native-country_Others,native-country_United-States
0,44,100479,12,0,0,0,0,48,0,0,...,0,0,1,0,0,0,0,0,0,1
1,57,477867,9,0,0,0,0,40,0,0,...,0,1,1,0,0,0,0,0,0,1
2,21,410439,10,0,0,0,0,24,0,0,...,0,0,0,0,0,1,0,0,0,1
3,21,195532,9,0,1,0,0,40,0,0,...,0,0,0,0,0,0,1,0,0,1
4,57,125000,15,0,0,0,0,35,0,0,...,0,0,1,0,0,0,0,0,0,1
5,61,268797,9,1,1,0,0,17,0,0,...,0,0,0,0,0,0,0,1,0,1
6,23,275818,10,0,1,0,1974,40,0,0,...,0,0,0,1,0,0,0,0,0,1
7,56,229335,9,0,1,0,0,40,0,0,...,0,0,0,1,0,0,0,0,0,1
8,33,269705,9,0,0,0,0,40,0,0,...,0,0,1,0,0,0,0,0,0,1
9,32,198211,10,0,0,0,0,38,0,0,...,0,0,0,1,0,0,0,0,0,1
10,42,204235,10,0,0,0,0,40,0,0,...,0,0,1,0,0,0,0,0,0,1
11,44,322044,10,1,0,0,0,40,0,0,...,0,0,0,0,0,1,0,0,0,1
12,26,37898,11,0,0,0,0,65,0,0,...,0,0,0,1,0,0,0,0,0,1
13,33,261639,10,1,0,4064,0,40,0,0,...,0,0,1,0,0,0,0,0,0,1
14,30,509364,10,0,0,0,0,40,0,0,...,0,0,0,0,0,1,0,0,0,1
15,43,109762,13,0,0,0,0,20,0,0,...,0,0,1,0,0,0,0,0,0,1
16,31,294870,12,0,0,0,0,40,0,1,...,0,0,1,0,0,0,0,0,0,1
17,44,259479,9,0,0,0,0,50,0,0,...,0,1,0,0,0,0,1,0,0,1
18,60,420842,12,0,1,0,0,40,0,0,...,0,0,0,0,1,0,0,0,1,0
19,29,185386,3,0,0,0,0,42,0,0,...,0,0,0,1,0,0,0,0,1,0
20,39,401832,10,0,0,0,0,48,0,0,...,0,0,1,0,0,0,0,0,0,1
21,60,772919,13,0,0,0,0,25,0,0,...,0,0,1,0,0,0,0,0,0,1
22,21,147655,9,0,1,0,0,40,0,0,...,0,0,0,0,0,1,0,0,0,1
23,31,201292,9,0,0,0,0,40,0,0,...,0,0,1,0,0,0,0,0,0,1
24,30,169002,11,0,0,0,0,40,0,0,...,0,0,0,0,0,1,0,0,0,1
25,29,161615,9,0,0,0,0,40,0,0,...,0,0,0,1,0,0,0,0,0,1
26,21,85733,10,0,1,0,0,40,1,0,...,0,0,0,0,0,1,0,0,0,1
27,37,233322,10,0,1,0,0,40,0,0,...,0,0,0,1,0,0,0,0,0,1
28,56,301835,3,0,0,0,0,40,0,0,...,0,0,0,1,0,0,0,0,0,1
29,29,159109,7,0,0,0,0,40,0,0,...,0,1,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35958,36,111545,9,0,0,0,0,70,0,0,...,0,0,1,0,0,0,0,0,0,1
35959,50,191598,9,0,0,0,1980,38,0,0,...,0,0,0,1,0,0,0,0,0,1
35960,41,89226,9,0,0,0,0,40,0,0,...,0,0,0,1,0,0,0,0,0,1
35961,34,334744,9,0,0,0,0,65,0,0,...,0,0,1,0,0,0,0,0,0,1
35962,58,49893,10,0,0,0,0,45,0,0,...,0,0,1,0,0,0,0,0,0,1
35963,20,70708,9,0,0,0,0,60,0,0,...,0,0,1,0,0,0,0,0,0,1
35964,23,148315,10,0,0,0,0,40,0,0,...,0,0,0,0,0,1,0,0,0,1
35965,43,64631,9,0,0,15024,0,50,0,0,...,0,0,1,0,0,0,0,0,0,1
35966,21,161051,10,1,1,0,0,4,0,0,...,1,0,0,0,0,1,0,0,0,1
35967,41,350387,13,0,0,0,0,40,0,0,...,0,0,0,1,0,0,0,0,0,1
35968,34,37676,13,0,0,0,0,50,0,0,...,0,0,1,0,0,0,0,0,0,1
35969,27,204373,10,1,1,0,0,40,0,0,...,0,0,0,1,0,0,0,0,0,1
35970,25,124111,13,0,1,0,0,40,0,0,...,0,0,0,0,0,1,0,0,0,1
35971,38,43770,10,0,1,4650,0,72,0,0,...,0,0,0,1,0,0,0,0,0,1
35972,54,91506,10,0,0,0,0,65,0,0,...,0,0,1,0,0,0,0,0,0,1
35973,46,27847,9,0,0,0,0,48,0,0,...,0,0,1,0,0,0,0,0,0,1
35974,42,308279,13,0,0,0,0,21,0,0,...,0,0,1,0,0,0,0,0,0,1
35975,21,140001,10,0,0,0,0,30,0,0,...,0,0,0,0,0,1,0,0,0,1
35976,58,87510,6,0,0,0,0,40,0,0,...,0,0,1,0,0,0,0,0,0,1
35977,27,604045,13,0,0,0,0,40,0,0,...,0,0,0,1,0,0,0,0,0,1
35978,45,90992,9,0,0,0,0,70,0,0,...,0,1,1,0,0,0,0,0,0,1
35979,51,73493,10,0,1,0,0,60,0,0,...,0,0,0,1,0,0,0,0,0,1
35980,20,177896,9,1,0,0,0,40,0,0,...,0,0,0,0,1,0,0,0,0,1
35981,44,248476,10,0,0,0,0,45,0,0,...,0,0,1,0,0,0,0,0,0,1
35982,39,232854,9,0,0,0,0,40,0,0,...,0,1,0,1,0,0,0,0,0,1
35983,25,108001,10,0,0,0,0,45,0,0,...,0,0,1,0,0,0,0,0,0,1
35984,33,246291,13,0,1,0,0,46,0,0,...,0,0,0,1,0,0,0,0,0,1
35985,23,206129,11,1,1,0,0,40,0,0,...,0,0,0,0,0,0,1,0,0,1
35986,42,76487,9,0,0,0,0,45,0,0,...,0,0,1,0,0,0,0,0,0,1
35987,33,37274,13,0,0,0,0,65,0,0,...,0,0,1,0,0,0,0,0,0,1